# WDA domain
DOMAIN = "wda_sensor"
SENSOR_UPDATE_SIGNAL = "WDA_SENSOR_OPTIONS_UPDATED"
NOT_SELECTED_VALUE = "not_selected"

# Defaults
DEFAULT_MIN_COOLANT_TEMP = 40
DEFAULT_MAX_COOLANT_TEMP = 80
DEFAULT_TARGET_ROOM_TEMP = 21.5
DEFAULT_HEATING_CURVE = 80
DEFAULT_HUMIDITY_THRESHOLD = 50
DEFAULT_ROOM_TEMP_CORRECTION = 2.0
DEFAULT_WIND_CORRECTION = 0.2
DEFAULT_HUMIDITY_CORRECTION = 0.05

# Default exponent range
DEFAULT_EXP_MIN = 1.2
DEFAULT_EXP_MAX = 2.2

# Graph sensor X range
GRAPH_MIN_OUTSIDE_TEMP = -25
GRAPH_MAX_OUTSIDE_TEMP = 20

# Update interval (seconds)
DEFAULT_UPDATE_INTERVAL = 3600
UPDATE_INTERVAL_CHOICES = {
    300: "5m",
    600: "10m",
    900: "15m",
    1200: "20m",
    1800: "30m",
    3600: "1h",
    7200: "2h"
}
